# Aux

In [ ]:
import numpy as np
import pennylane as qml 
import torch

def create_circuit(n_qubits,n_layers=None,circ = "simplified_two_design",fim=False, shots=None):

    dev = qml.device("default.qubit.torch", wires=n_qubits, shots=shots)

    def RZRY(params):
        #qml.SpecialUnitary(params, wires=range(n_qubits))
        #qml.SimplifiedTwoDesign(initial_layer_weights=init_params, weights=params, wires=range(n_qubits))
        #qml.AngleEmbedding(params,wires=range(n_qubits))
        for q in range(n_qubits):
            qml.Hadamard(wires=q)

        for w in range(n_layers): 
            for q in range(n_qubits):
                index = w * (2*n_qubits) + q * 2
                qml.RZ(params[index],wires=q)
                qml.RY(params[index + 1],wires=q)
        
        qml.broadcast(qml.CNOT , wires=range(n_qubits), pattern="all_to_all")
        
        return qml.probs(wires=range(n_qubits))

    def S2D(init_params,params,measurement_qubits=0,prod_approx=False):
        #qml.SpecialUnitary(params, wires=range(n_qubits))
        qml.SimplifiedTwoDesign(initial_layer_weights=init_params, weights=params, wires=range(n_qubits))
        
        #qml.broadcast(qml.CNOT , wires=range(n_qubits), pattern="all_to_all")
        if not prod_approx:
            return qml.probs(wires=list(range(measurement_qubits)))
        else:
            return [qml.probs(i) for i in range(measurement_qubits)]

    def SU(params):
        qml.SpecialUnitary(params, wires=range(n_qubits))
        
        ZZ = qml.operation.Tensor(qml.PauliZ(0), qml.PauliZ(1))
        for i in range(2,n_qubits):
            ZZ = qml.operation.Tensor(ZZ, qml.PauliZ(i))

        return qml.expval(ZZ)
    
    def simmpleRZRY(params,cnots=True):
        qml.broadcast(qml.Hadamard, wires=range(n_qubits), pattern="single")
        qml.broadcast(qml.RZ, wires=range(n_qubits), pattern="single", parameters=params[0])
        qml.broadcast(qml.RY, wires=range(n_qubits), pattern="single", parameters=params[1])
        if cnots:
            qml.broadcast(qml.CNOT, wires=range(n_qubits), pattern="chain")

            return qml.expval(qml.PauliZ(n_qubits-1))
        else:
            ZZ = qml.operation.Tensor(qml.PauliZ(0), qml.PauliZ(1))
            for i in range(2,n_qubits):
                ZZ = qml.operation.Tensor(ZZ, qml.PauliZ(i))

            return qml.expval(ZZ)
        
    def RY(params,y=True,probs=False,prod=False, entanglement=None):
        #qml.broadcast(qml.Hadamard, wires=range(n_qubits), pattern="single")
        qml.broadcast(qml.RY, wires=range(n_qubits), pattern="single", parameters=params)
        #qml.broadcast(qml.CZ, wires=range(n_qubits), pattern="all_to_all")

        if entanglement=="all_to_all":
            qml.broadcast(qml.CNOT, wires=range(n_qubits), pattern="all_to_all")
        
        if y==True:
            #YY = qml.operation.Tensor(qml.PauliY(0), qml.PauliY(1))
            YY = [qml.PauliZ(0), qml.PauliZ(1)]
            for i in range(2,n_qubits):
                #YY = qml.operation.Tensor(YY, qml.PauliY(i))
                YY.append(qml.PauliZ(i))
            
            #return [qml.expval(i) for i in YY]
            return qml.expval(YY)

        elif probs==False:

            ZZ = qml.operation.Tensor(qml.PauliZ(0), qml.PauliZ(1))
            #ZZ = [qml.PauliZ(0), qml.PauliZ(1)]
            for i in range(2,n_qubits):
                ZZ = qml.operation.Tensor(ZZ, qml.PauliZ(i))        
                #ZZ.append(qml.PauliZ(i))        

            #return [qml.expval(i) for i in ZZ]
            return qml.expval(ZZ)

        else:
            if prod:
                return [qml.probs(i) for i in range(n_qubits)]
            else:
                return qml.probs(wires=range(n_qubits))
            
        
        
    def GHZ(params,measurement_qubits=0):
        qml.RY(params,wires=0)
        qml.broadcast(qml.CNOT, wires=range(n_qubits), pattern="chain")

        return qml.probs(wires=range(measurement_qubits))

    def random_product_state(params,gate_sequence=None):
                
        for i in range(n_qubits):
            qml.RY(np.pi / 4, wires=i)

        for ll in range(len(params)):

            for i in range(n_qubits):
                gate_sequence["{}{}".format(ll,i)](params[ll][i], wires=i)

            #for i in range(n_qubits - 1):
                #qml.CZ(wires=[i, i + 1])
    def SEL(params, measurement_qubits=0):
        qml.StronglyEntanglingLayers(params, wires=range(n_qubits))
        return qml.probs(wires=range(measurement_qubits))
    
    def RL(params, measurement_qubits=0):
        qml.RandomLayers(params, ratio_imprim=0.8 ,imprimitive=qml.CZ, wires=range(n_qubits))
        return qml.probs(wires=range(measurement_qubits))
    
    if circ == "rzry":
        qcircuit = RZRY
    elif circ == "simplified_two_design":
        qcircuit = S2D
    elif circ == "special_unitary":
        qcircuit = SU
    elif circ == "simpleRZRY":
        qcircuit = simmpleRZRY
    elif circ == "RY":
        qcircuit = RY
    elif circ == "ghz":
        qcircuit = GHZ
    elif circ == "random_product_state":
        qcircuit = random_product_state
    elif circ == "SEL":
        qcircuit = SEL
    elif circ == "RL":
        qcircuit = RL
    if not fim:
        circuit = qml.QNode(qcircuit, dev,interface="torch", diff_method="backprop")
    else:
        circuit = qml.QNode(qcircuit, dev)

    return circuit

def compute_gradient(log_prob, w):
    """Compute gradient of the log probability with respect to weights.
    
    Args:
    - log_prob (torch.Tensor): The log probability tensor.
    - w (torch.Tensor): The weights tensor, with requires_grad=True.

    Returns:
    - numpy.ndarray: The gradient of log_prob with respect to w, flattened.
    """
    if w.grad is not None:
        w.grad.zero_()
    log_prob.backward(retain_graph=True)
    
    if w.grad is None:
        raise ValueError("The gradient for the given log_prob with respect to w is None.")
    
    return w.grad.view(-1).detach().numpy()

def policy(probs, policy_type="contiguous-like", n_actions=2, n_qubits=1):

    if policy_type == "contiguous-like":
        return probs
    elif policy_type == "parity-like":
        policy = torch.zeros(n_actions)
        for i in range(len(probs)):
            a=[]
            for m in range(int(np.log2(n_actions))):
                if m==0:    
                    bitstring = np.binary_repr(i,width=n_qubits)
                else:
                    bitstring = np.binary_repr(i,width=n_qubits)[:-m]
                
                a.append(bitstring.count("1") % 2)
            policy[int("".join(str(x) for x in a),2)] += probs[i]

        return policy    
    
def compute_policy_and_gradient(args):
    n_qubits, shapes, type , n_actions, policy_type, clamp = args

    if policy_type == "parity-like":
        measure_qubits = n_qubits
    else:
        measure_qubits = int(np.log2(n_actions))

    qc = create_circuit(n_qubits, circ=type, fim=False, shots=None)

    if type == "simplified_two_design":
        weights = [np.random.uniform(-np.pi,np.pi,size=shape) for shape in shapes]    
        weights_tensor_init = torch.tensor(weights[0], requires_grad=False)
        weights_tensor_params = torch.tensor(weights[1], requires_grad=True)
        
        probs = qc(weights_tensor_init,weights_tensor_params, measurement_qubits=measure_qubits)

    else:
        weights = [np.random.uniform(-np.pi,np.pi,size=shape) for shape in shapes]    
        weights_tensor_params = torch.tensor(weights, requires_grad=True)

        probs = qc(weights_tensor_params, measurement_qubits=measure_qubits)

    pi = policy(probs, policy_type=policy_type, n_actions=n_actions, n_qubits=n_qubits)
    if clamp is not None:
        pi = torch.clamp(pi, clamp, 1)

    dist = torch.distributions.Categorical(probs=pi)
    
    action = dist.sample()
    log_prob = dist.log_prob(action)

    gradient_no_clamp = np.linalg.norm(compute_gradient(log_prob, weights_tensor_params), 2)
    return gradient_no_clamp


In [ ]:
def reinforce(policy, optimizer, env, n_episodes=1000, max_t=1000, gamma=1.0, print_every=5):
    scores_deque = deque(maxlen=print_every)
    scores = []
    average_scores = []
    runtime_sum = 0
    for e in range(1, n_episodes):
        saved_log_probs = []
        rewards = []
        state = env.reset()
        # Collect trajectory
        for t in range(max_t):
            # Sample the action from current policy
            if t==0:
                state_tensor = torch.tensor(state[0]).float()
            else:
                state_tensor = torch.tensor(state).float()
            action, log_prob, _, = policy.sample(state_tensor)
            saved_log_probs.append(log_prob)
            state, reward, done, _, _ = env.step(action)
            rewards.append(reward)
            if done:
                break

    # Total expected reward
        scores_deque.append(sum(rewards))
        scores.append(sum(rewards))
    #standardized returns
        R=0
        policy_loss = []
        returns = []
        for r in rewards[::-1]:
            R = r + gamma * R
            returns.insert(0,R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + np.finfo(np.float32).eps)

        for log_prob, R in zip(saved_log_probs, returns):
            policy_loss.append(-log_prob * R)

        policy_unsqueezed = [torch.unsqueeze(loss, 0) for loss in policy_loss]
        policy_sum = torch.cat(policy_unsqueezed).sum()

    # Backpropagation
        start_time = time.time()
        optimizer.zero_grad()
        policy_sum.backward()
        optimizer.step()
        end_time = time.time()
        runtime = end_time-start_time
        
        runtime_sum += runtime
        if e % print_every == 0:
            print('Episode {}\tLast reward: {:.2f}\tLast {}\tEpisodes average reward: {:.2f}\tRuntime: {:.2f}'.format(e, scores_deque[-1], print_every, np.mean(scores_deque), runtime_sum))
            runtime_sum = 0
        if np.mean(scores_deque) == 500:
            print('Environment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(e, np.mean(scores_deque)))
            break
    return scores, policy.gradient_list, average_scores  

In [ ]:
    def save_training_data(self):
        ''' 
        Saves training data into json files
        '''
        current_directory = os.path.dirname(__file__)
        folder_name = f"{str(self.env_name)}_{self.pqc.policy.post_processing}_{self.pqc.circuit.n_layers}"
        folder_path = os.path.join(current_directory, folder_name)
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)

        episode_data = [self.scores_deque, 
                        self.runtime, 
                        self.loss.item(), 
                        tensor_to_list(self.pqc.get_gradients()[0]), 
                        tensor_to_list(self.pqc.get_gradients()[1])]

        if folder_path is not None:
            file_path = os.path.join(self.folder_path, f"{self.file_name}.json")
            if os.path.exists(file_path):
                with open(file_path, 'r') as f:
                    existing_data = json.load(f)
                existing_data.append(episode_data)
                with open(file_path, 'w') as f:
                    json.dump(existing_data, f, indent=4)
            else:
                with open(file_path, 'w') as f:
                    json.dump([episode_data], f, indent=4)

# Policy Gradient Algorithm

In [1]:
import pennylane as qml
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter

import gym
from collections import deque

from tensorboard.backend.event_processing import event_accumulator
from joblib import Parallel, delayed
import os
import json
import time

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (10, 5)

In [ ]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir ../../data

# Utils


In [2]:
#utils

def tensor_to_list(tensor):
    """
    Convert a tensor or numpy array to a nested list.
    """
    if isinstance(tensor, list):
        return [tensor_to_list(t) for t in tensor]
    elif isinstance(tensor, dict):
        return {key: tensor_to_list(value) for key, value in tensor.items()}
    elif isinstance(tensor, np.ndarray):
        return tensor.tolist()
    elif isinstance(tensor, torch.Tensor):
        return tensor.tolist()
    else:
        return tensor

def measure_probs(qubits):
    return qml.probs(wires=range(qubits)) 

def measure_expval_pairs(qubits):
    expvals = []
    for i in range(qubits // 2):
        expvals.append(qml.expval(qml.PauliZ(2*i) @ qml.PauliZ(2*i + 1)))
    return expvals
    
def create_optimizer_with_lr(params, lr_list):
    optimizer = torch.optim.Adam([
        {'params': params, 'lr': lr} for params, lr in zip(params, lr_list)
    ])
    return optimizer

def jerbi_circuit(n_qubits, n_layers, shots, input_scaling, diff_method, weight_init, input_init, measure, measure_qubits):

    if shots is None:
        dev = qml.device("default.qubit", wires=n_qubits)
    else:
        dev = qml.device("default.qubit", wires=n_qubits, shots=shots)
    
    if n_layers < 1:
        raise ValueError("Number of layers can't take values below 1")
    
    weight_shapes = {"params": (n_layers + 1, n_qubits, 2),
                    "input_params": (n_layers, n_qubits, 2)}
    init_method   = {"params": weight_init,
                    "input_params": input_init}
    
    @qml.qnode(dev, interface='torch', diff_method=diff_method)
    def qnode(inputs, params, input_params):
    #in case n_qubits != input length
        if n_qubits > len(inputs) and n_qubits % len(inputs) == 0:
            multiplier = n_qubits // len(inputs)
            inputs = torch.cat([inputs] * multiplier)
        elif n_qubits != len(inputs) and n_qubits % len(inputs) != 0:
            raise ValueError('Number of qubits cannot be divided by input lenght')

    #hadamard
        qml.broadcast(qml.Hadamard, wires=range(n_qubits), pattern="single")
        
        for layer in range(n_layers):
            for wire in range(n_qubits):
                qml.RZ(params[layer][wire][0], wires=wire)
                qml.RY(params[layer][wire][1], wires=wire)

            qml.broadcast(qml.CNOT, wires=range(n_qubits), pattern="chain")

            if input_scaling:
                for wire in range(n_qubits):
                    qml.RY(input_params[layer][wire][0] * inputs[wire], wires=wire)
                    qml.RZ(input_params[layer][wire][1] * inputs[wire], wires=wire)
            else:
                for wire in range(n_qubits):
                    qml.RY(inputs[wire], wires=wire)
                    qml.RZ(inputs[wire], wires=wire)

        for wire in range(n_qubits):
            qml.RZ(params[-1][wire][0], wires=wire)
            qml.RY(params[-1][wire][1], wires=wire)
            
        return measure(measure_qubits)

    model = qml.qnn.TorchLayer(qnode, weight_shapes=weight_shapes, init_method=init_method)  
    
    return model
    
def S2D(n_qubits, n_layers, shots, input_scaling, diff_method, weight_init, input_init, measure_type, observables, measure_qubits):

    dev = qml.device("default.qubit", wires=n_qubits)

    observables = observables if observables is not None else None
    
    shapes = qml.SimplifiedTwoDesign.shape(n_layers=n_layers, n_wires=n_qubits)

    weight_shapes = {"params": shapes[1],
                     "input_params": shapes[0]}
    
    init_method   = {"params": weight_init,
                     "input_params": input_init}

    @qml.qnode(dev, interface='torch', diff_method='parameter-shift')
    def qnode(inputs, params, input_params):

        return measure_selection(measure_type, observables, measure_qubits)

    model = qml.qnn.TorchLayer(qnode, weight_shapes=weight_shapes, init_method=init_method)

    return model

# Classes

In [3]:
class CircuitGenerator(nn.Module):

    def __init__(self, n_qubits, n_layers,  shots= None, input_scaling=True, design='jerbi_circuit', diff_method = 'backprop', weight_init=torch.nn.init.uniform_, input_init = torch.nn.init.ones_, measure = None, measure_qubits = None):
        super(CircuitGenerator, self).__init__()
        '''

        Creates a parameterized quantum circuit based on the arguments:

            n_qubits(int) = Number of qubits
            n_layers(int) = Number of layers (0 if no data re-uploading)
            shots(int) = Number of times the circuit gets executed
            input_scaling(bool) = Input parameters are used if True (input*input_params)
            design(str) = The PQC ansatz design ('jerbi_circuit')
            diff_method(str) = Differentiation method ('best', 'backprop', 'parameter-shift', ...)
            weight_init (torch.nn.init) = How PQC weights are initialized (.uniform_, .ones_, ...)
            input_init (torch.nn.init) = How input weights are initialized (.uniform_, .ones_, ...)
            measure (function) = Measure function (measure_probs, measure_expval_pairs)
            measure_qubits (int) = Number of qubits to be measured (in some cases might be equal to the number of qubits)
            
        '''
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        self.shots = shots
        self.input_scaling = input_scaling
        self.design = design
        self.diff_method = diff_method
        self.weight_init = weight_init
        self.input_init = input_init
        if measure is None:
            self.measure = measure_probs
        else:
            self.measure = measure

        if measure_qubits is None:
            self.measure_qubits = n_qubits
        else:
            self.measure_qubits = measure_qubits

        if self.design == 'jerbi_circuit':
            self.circuit = jerbi_circuit(n_qubits = self.n_qubits,
                                        n_layers = self.n_layers,
                                        shots = self.shots,
                                        input_scaling = self.input_scaling,
                                        diff_method = self.diff_method,
                                        weight_init = self.weight_init,
                                        input_init = self.input_init,
                                        measure = self.measure,
                                        measure_qubits = self.measure_qubits)
        else:
            raise ValueError("Unsupported circuit type")

    def input(self,inputs):

        outputs = self.circuit(inputs)
        return outputs

In [4]:
class PolicyType(nn.Module):
    
    def __init__(self, n_qubits, n_actions, post_processing = 'raw_contiguous'):
        self.n_actions = n_actions
        self.n_qubits = n_qubits
        self.post_processing = post_processing
        self.T = 0.5

    def input(self,probs):
        if self.post_processing == 'raw_contiguous':
            policy = self.raw_contiguous(probs)
        elif self.post_processing == 'raw_parity':
            policy = self.raw_parity(probs)
        elif self.post_processing == 'softmax':
            policy = self.softmax(probs)
        else:
            raise ValueError("Invalid post-processing method specified.")
        return policy

    def raw_contiguous(self,probs):
        
        probs_flatten = probs.flatten()
        chunk_size = len(probs_flatten) // self.n_actions
        remainder = len(probs_flatten) % self.n_actions

        policy = []

        for i in range(self.n_actions):
            start = i * chunk_size
            end = (i + 1) * chunk_size

            if i < remainder:
                end += 1

            # Update the original policy list instead of creating a new one
            policy.append(sum(probs_flatten[start:end]))

        policy_tensor = torch.stack(policy)
        return policy_tensor
        
    def raw_parity(self,probs):

        if self.n_actions % 2 != 0:
            raise ValueError('For parity-like policy, n_actions must be an even number')
        
        probs_flatten = probs.flatten()
        policy = torch.zeros(self.n_actions)
        counter = 0
        for prob in probs_flatten:
            policy[counter] += prob
            counter += 1
            if counter == self.n_actions:
                counter = 0
        
        return policy
    
    def softmax(self, probs):
        if len(probs) == self.n_actions:
            scaled_output = probs * self.T
            softmax_output = F.softmax(scaled_output, dim=0)
            return softmax_output
        else:
            probs_flatten = probs.flatten()
            chunk_size = len(probs_flatten) // self.n_actions
            remainder = len(probs_flatten) % self.n_actions

            policy = []

            for i in range(self.n_actions):
                start = i * chunk_size
                end = (i + 1) * chunk_size

                if i < remainder:
                    end += 1

                # Update the original policy list instead of creating a new one
                policy.append(sum(probs_flatten[start:end]))
            policy_tensor = torch.stack(policy)
            softmax_output = F.softmax(policy_tensor * self.T, dim=0)
            return softmax_output

In [5]:
class QuantumPolicyModel(nn.Module):
    
    def __init__(self, circuit, policy):
        super(QuantumPolicyModel, self).__init__()
        self.circuit = circuit
        self.policy = policy

    def forward(self, inputs):
        '''
        Input state is fed to the circuit - its output is then fed to the post processing 
        '''
        probs = self.circuit.input(inputs)
        probs_processed = self.policy.input(probs)
        return probs_processed
    
    def sample(self, inputs):
        '''
        Samples an action from the action probability distribution aka policy
        '''
        policy = self.forward(inputs)
        print(policy)
        dist = torch.distributions.Categorical(policy)
        action = dist.sample()
        return action.item(), dist.log_prob(action), policy
    
    def T_schedule(self):

        increase_rate = 0.005  # Decay rate
        print(self.policy.T)
        self.policy.T += increase_rate

    def get_parameters(self):
        '''
        Returns the values of each set of parameters
        '''
        parameter_values = [param.clone().detach().numpy().flatten() for param in self.circuit.parameters()]
        return parameter_values
    
    def get_gradients(self):
        '''
        Returns the gradient values of each set of parameters
        '''
        gradients = [torch.flatten(param.grad.clone().detach()) if param.grad is not None else torch.flatten(torch.zeros_like(param)) for name, param in self.circuit.named_parameters()]
        return gradients

In [6]:
class ReinforceUpdate():

    def __init__(self, pqc, optimizer, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name = None):
        
        self.pqc = pqc
        self.optimizer = optimizer
        self.env = env
        self.env_name = env_name
        self.n_episodes = n_episodes
        self.max_t = max_t
        self.gamma = gamma
        self.scores_deque = deque(maxlen=print_every)
        self.print_every = print_every
        self.verbose = verbose
        self.file_name = file_name
        self.running_reward = 10

    def get_trajectory(self):

        self.saved_log_probs = []
        self.rewards = []
        state = self.env.reset()
        for t in range(self.max_t):
            if t == 0:
                state_tensor = torch.tensor(state[0]).float()
            else:
                state_tensor = torch.tensor(state).float()
            action, log_prob, _, = self.pqc.sample(state_tensor)
            state, reward, done, _, _ = self.env.step(action)
            
            self.saved_log_probs.append(log_prob)
            self.rewards.append(reward)

            if done:
                self.scores_deque.append(sum(self.rewards))
                break

    def update_policy(self):

        R = 0
        policy_loss = []
        returns = []
        for r in self.rewards[::-1]:
            R = r + self.gamma * R
            returns.insert(0, R)
        returns = torch.tensor(returns)
        returns = (returns - returns.mean()) / (returns.std() + 1e-8)

        for log_prob, ret in zip(self.saved_log_probs, returns):
            policy_loss.append(-log_prob * ret)

        policy_unsqueezed = [torch.unsqueeze(loss, 0) for loss in policy_loss]
        self.loss = torch.cat(policy_unsqueezed).sum()

        self.optimizer.zero_grad()
        self.loss.backward()    
        self.optimizer.step()
        
    def save_agent_data(self,main_path):

        agent_variables = {
            "Number of Qubits": self.pqc.circuit.n_qubits,
            "Number of Layers": self.pqc.circuit.n_layers,
            "Shots": self.pqc.circuit.shots,
            "Input Scaling": self.pqc.circuit.input_scaling,
            "Design": self.pqc.circuit.design,
            "Differentiation Method": self.pqc.circuit.diff_method,
            "Weight Initiation": str(self.pqc.circuit.weight_init),
            "Input_init": str(self.pqc.circuit.input_init),
            "Measure": str(self.pqc.circuit.measure),
            "Measure Qubits": self.pqc.circuit.measure_qubits,
            "Policy Type": self.pqc.policy.post_processing,
            "Optimizers": str(self.optimizer),
            "Envinronment Name": str(self.env_name),
            "Gamma (discounting factor)": self.gamma,
        }

        with open(os.path.join(main_path, "agent_characteristics.json"), "w") as f:
            json.dump(agent_variables, f, indent=4)

    def save_data(self,main_path):

        run= os.path.join(main_path,str(self.file_name)+'_data.npz')

        if not os.path.exists(main_path):
            os.makedirs(main_path)

        if os.path.exists(run):
            data = np.load(run, allow_pickle=True)
            old_episode_reward = data['episode_reward'].tolist()
            old_loss = data['loss'].tolist()
            old_runtime = data['runtime'].tolist()
            old_params_gradients = data['params_gradients'].tolist()
            old_input_params_gradients = data['input_params_gradients'].tolist()
        else:
            old_episode_reward = []
            old_loss = []
            old_runtime = []
            old_params_gradients = []
            old_input_params_gradients = []


        old_episode_reward.append(self.scores_deque[-1])
        old_loss.append(self.loss.item())
        old_runtime.append(self.runtime)
        old_params_gradients.append(tensor_to_list(self.pqc.get_gradients()[0]))
        old_input_params_gradients.append(tensor_to_list(self.pqc.get_gradients()[1]))

        np.savez_compressed(run, episode_reward = np.array(old_episode_reward),
                                 loss = np.array(old_loss),
                                 runtime = np.array(old_runtime),
                                 params_gradients = np.array(old_params_gradients), 
                                 input_params_gradients = np.array(old_input_params_gradients))
        
        del old_episode_reward[:]
        del old_loss[:]
        del old_runtime[:]
        del old_params_gradients[:]
        del old_input_params_gradients[:]

    def writer_function(self, writer, iteration):

        writer.add_scalar("Episode Reward", np.mean(self.scores_deque), global_step=iteration)
        writer.add_scalar("Running Reward", self.running_reward, global_step=iteration)
        writer.add_scalar("Runtime", self.runtime, global_step=iteration)
        writer.add_scalar("Loss", self.loss.item(), global_step=iteration)
    
    def train(self):
        
        logs_dir = "../../data"
        os.makedirs(logs_dir, exist_ok=True)
        envinronment_folder = os.path.join(logs_dir, self.env_name)
        os.makedirs(envinronment_folder, exist_ok=True)
        experiment_folder = f"{self.pqc.policy.post_processing}_{self.pqc.circuit.n_layers}layer"
        experiment_path = os.path.join(envinronment_folder, experiment_folder)
        os.makedirs(experiment_path, exist_ok=True)
        run = os.path.join(experiment_path,str(self.file_name))
        os.makedirs(run, exist_ok=True)
        writer = SummaryWriter(log_dir=run)
        self.save_agent_data(experiment_path)
        
        for i in range(1, self.n_episodes):
            start_time = time.time()
            self.get_trajectory()
            self.pqc.T_schedule()
            self.update_policy()
            end_time = time.time()
            self.runtime = end_time - start_time
            self.writer_function(writer,i)
            self.save_data(run)
            self.running_reward = (self.running_reward * 0.99) + (len(self.rewards) * 0.01)
            
            if self.running_reward > self.env.spec.reward_threshold:
                print('Environment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i, np.mean(self.scores_deque)))
                break
            elif i % self.print_every == 0 and self.verbose == 1:
                print('Episode {}\tLast reward: {:.2f}\tLast {} Episodes average reward: {:.2f}\tRuntime: {:.2f}\t {:.2f}\t'.format(i, self.scores_deque[-1], self.print_every, np.mean(self.scores_deque), self.runtime, self.running_reward))

        #self.event_acumulator(run)

# Single agent runs

In [50]:
n_qubits = 4
n_layers = 4      #set to 1 if data_reuploading is off
n_actions = 2
shots = None
input_scaling = False
design = 'jerbi_circuit' 
diff_method = 'adjoint' 
weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
input_init = torch.nn.init.uniform_
measure = measure_expval_pairs
measure_qubits = None
circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init, measure=measure)

post_processing = 'softmax'
policy_type = PolicyType(n_qubits, n_actions, post_processing = post_processing)


pqc = QuantumPolicyModel(circuit,policy_type)


pqc = pqc
lr_list= [0.01,0.08]
params= circuit.parameters()
optimizers= create_optimizer_with_lr(params,lr_list)
env_name = 'CartPole-v1'
env = gym.make(env_name)
n_episodes = 500
max_t = 500
gamma = 0.98
print_every = 5
verbose = 1

reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose)
reinforce_update.train()

tensor([0.6052, 0.3948], grad_fn=<SoftmaxBackward0>)
tensor([0.5679, 0.4321], grad_fn=<SoftmaxBackward0>)
tensor([0.6040, 0.3960], grad_fn=<SoftmaxBackward0>)
tensor([0.5698, 0.4302], grad_fn=<SoftmaxBackward0>)
tensor([0.5150, 0.4850], grad_fn=<SoftmaxBackward0>)
tensor([0.4899, 0.5101], grad_fn=<SoftmaxBackward0>)
tensor([0.4810, 0.5190], grad_fn=<SoftmaxBackward0>)
tensor([0.4840, 0.5160], grad_fn=<SoftmaxBackward0>)
tensor([0.5006, 0.4994], grad_fn=<SoftmaxBackward0>)
tensor([0.4805, 0.5195], grad_fn=<SoftmaxBackward0>)


c:\Users\Bernardo\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


tensor([0.4780, 0.5220], grad_fn=<SoftmaxBackward0>)
tensor([0.4765, 0.5235], grad_fn=<SoftmaxBackward0>)
tensor([0.4811, 0.5189], grad_fn=<SoftmaxBackward0>)
tensor([0.5173, 0.4827], grad_fn=<SoftmaxBackward0>)
tensor([0.4758, 0.5242], grad_fn=<SoftmaxBackward0>)
tensor([0.5011, 0.4989], grad_fn=<SoftmaxBackward0>)
tensor([0.4727, 0.5273], grad_fn=<SoftmaxBackward0>)
tensor([0.4850, 0.5150], grad_fn=<SoftmaxBackward0>)
tensor([0.5304, 0.4696], grad_fn=<SoftmaxBackward0>)
tensor([0.4746, 0.5254], grad_fn=<SoftmaxBackward0>)
tensor([0.4737, 0.5263], grad_fn=<SoftmaxBackward0>)
0.5
tensor([0.5934, 0.4066], grad_fn=<SoftmaxBackward0>)
tensor([0.5914, 0.4086], grad_fn=<SoftmaxBackward0>)
tensor([0.5755, 0.4245], grad_fn=<SoftmaxBackward0>)
tensor([0.5929, 0.4071], grad_fn=<SoftmaxBackward0>)
tensor([0.5745, 0.4255], grad_fn=<SoftmaxBackward0>)
tensor([0.5423, 0.4577], grad_fn=<SoftmaxBackward0>)
tensor([0.5711, 0.4289], grad_fn=<SoftmaxBackward0>)
tensor([0.5352, 0.4648], grad_fn=<SoftmaxB

KeyboardInterrupt: 

# Multiple agent runs


## Raw Contiguous


In [8]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 1      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_probs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init)


    post_processing = 'raw_parity'
    policy_type = PolicyType(n_qubits, n_actions)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 0: Training completed', 'Agent 1: Training completed', 'Agent 2: Training completed', 'Agent 3: Training completed', 'Agent 4: Training completed', 'Agent 5: Training completed', 'Agent 6: Training completed', 'Agent 7: Training completed', 'Agent 8: Training completed', 'Agent 9: Training completed']


In [9]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 1      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_probs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init)


    post_processing = 'raw_parity'
    policy_type = PolicyType(n_qubits, n_actions)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i+10) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 10: Training completed', 'Agent 11: Training completed', 'Agent 12: Training completed', 'Agent 13: Training completed', 'Agent 14: Training completed', 'Agent 15: Training completed', 'Agent 16: Training completed', 'Agent 17: Training completed', 'Agent 18: Training completed', 'Agent 19: Training completed']


## Raw Parity

In [10]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 1      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_probs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init)


    post_processing = 'raw_parity'
    policy_type = PolicyType(n_qubits, n_actions, post_processing=post_processing)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 0: Training completed', 'Agent 1: Training completed', 'Agent 2: Training completed', 'Agent 3: Training completed', 'Agent 4: Training completed', 'Agent 5: Training completed', 'Agent 6: Training completed', 'Agent 7: Training completed', 'Agent 8: Training completed', 'Agent 9: Training completed']


In [11]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 1      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_probs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init)


    post_processing = 'raw_parity'
    policy_type = PolicyType(n_qubits, n_actions, post_processing=post_processing)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i+10) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 10: Training completed', 'Agent 11: Training completed', 'Agent 12: Training completed', 'Agent 13: Training completed', 'Agent 14: Training completed', 'Agent 15: Training completed', 'Agent 16: Training completed', 'Agent 17: Training completed', 'Agent 18: Training completed', 'Agent 19: Training completed']


## Softmax


In [7]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 4      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_expval_pairs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init, measure=measure)


    post_processing = 'softmax'
    policy_type = PolicyType(n_qubits, n_actions, post_processing=post_processing)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i+10) for i in range(num_agents))
    print(results)
    time.sleep(100)

In [ ]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 6      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_expval_pairs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init, measure=measure)


    post_processing = 'softmax'
    policy_type = PolicyType(n_qubits, n_actions, post_processing=post_processing)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i+10) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 10: Training completed', 'Agent 11: Training completed', 'Agent 12: Training completed', 'Agent 13: Training completed', 'Agent 14: Training completed', 'Agent 15: Training completed', 'Agent 16: Training completed', 'Agent 17: Training completed', 'Agent 18: Training completed', 'Agent 19: Training completed']


In [ ]:
# Parallel runs
current_directory = os.getcwd()

def train_agents(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name):

    reinforce_update = ReinforceUpdate(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, file_name)
    reinforce_update.train()

    return f"Agent {file_name}: Training completed"

if __name__ == "__main__":
    n_qubits = 4
    n_layers = 8      #set to 1 if data_reuploading is off
    n_actions = 2
    shots = None
    input_scaling = False
    design = 'jerbi_circuit' 
    diff_method = 'adjoint' 
    weight_init = lambda shape, dtype=torch.float: torch.FloatTensor(shape).uniform_(-np.pi, np.pi)
    input_init = torch.nn.init.uniform_
    measure = measure_expval_pairs
    measure_qubits = None
    circuit = CircuitGenerator(n_qubits, n_layers, weight_init=weight_init, measure=measure)


    post_processing = 'softmax'
    policy_type = PolicyType(n_qubits, n_actions, post_processing=post_processing)


    pqc = QuantumPolicyModel(circuit,policy_type)
    

    pqc = pqc
    lr_list= [0.01,0.08]
    params= circuit.parameters()
    optimizers= create_optimizer_with_lr(params,lr_list)
    env_name = 'CartPole-v1'
    env = gym.make(env_name)
    n_episodes = 500
    max_t = 500
    gamma = 0.98
    print_every = 10
    verbose = 1
        
    num_agents = 10

    results = Parallel(n_jobs=num_agents)(delayed(train_agents)(pqc, optimizers, env, env_name, n_episodes, max_t, gamma, print_every, verbose, i+10) for i in range(num_agents))
    print(results)
    time.sleep(100)

['Agent 10: Training completed', 'Agent 11: Training completed', 'Agent 12: Training completed', 'Agent 13: Training completed', 'Agent 14: Training completed', 'Agent 15: Training completed', 'Agent 16: Training completed', 'Agent 17: Training completed', 'Agent 18: Training completed', 'Agent 19: Training completed']
